### ISSUE TITLE
unfortunately app has stopped in android 6.0

### ISSUE THREAD

**Issue by sheryarshirazi** [EddyVerbruggen/Calendar-PhoneGap-Plugin#354] opened 2016-12-17 22:38 UTC
App unfortunately stopped when creating an event.
@EddyVerbruggen #android #6.0 #calendar

**Comment by RenateM** [comment] 2017-02-01 14:40
I am having the same issue, but only when using createEventWithOptions. 

The crash happens on this line in cordova.js
var msgs = nativeApiProvider.get().exec(bridgeSecret, service, action, callbackId, argsJson);
Parameter values:
bridgeSecret = 1584848331
service = "Calendar"
action = "createEventWithOptions"
callbackId = "Calendar1208308604"
argsJson = 
"[{"title":"Test","location":"Centurion, Gauteng, South Africa","notes":"Test","startTime":1485959400000,"endTime":1485960300000,"options":{"firstReminderMinutes":60,"secondReminderMinutes":null,"recurrence":"daily","recurrenceInterval":1,"recurrenceWeekstart":"MO","recurrenceByDay":null,"recurrenceByMonthDay":null,"recurrenceEndDate":null,"recurrenceCount":null,"calendarName":null,"calendarId":null,"url":null}}]"

Using:
cordova-plugin-calendar 4.5.5
cordova 6.4.0 
cordova android platform 6.1.0
Android OS 5.0.1

Any ideas as to why this is happening?

**Comment by RenateM** [comment] 2017-02-01 14:54
I see in the code for the createEvent method, provision is made for Android by using the createEventInteractively method in stead. The same provision for Android is not made in the createEventWithOptions method.

**Comment by EddyVerbruggen** [comment] 2017-02-01 15:32
@RenateM can you share the crash log (`adb logcat`)?

**Comment by RenateM** [comment] 2017-02-02 07:12
Hi @EddyVerbruggenVerbruggen 

I'm new to logcat. So I used Android Device Monitor to get the crash log. It seems like a whole load of greek to me, I hope you can make it out. Here is the part where I believe the error happened:


02-02 09:07:55.221: E/NetdConnector(3184): Error handling '613 IfaceClass active (null)': java.lang.NumberFormatException: Invalid int: "(null)"
02-02 09:07:55.251: E/AndroidRuntime(12942): FATAL EXCEPTION: pool-1-thread-4
02-02 09:07:55.251: E/AndroidRuntime(12942): Process: com.yyy.zzz, PID: 12942
02-02 09:07:55.251: E/AndroidRuntime(12942): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
02-02 09:07:55.251: E/AndroidRuntime(12942): 	at nl.xservices.plugins.accessor.AbstractCalendarAccessor.createEvent(AbstractCalendarAccessor.java:498)
02-02 09:07:55.251: E/AndroidRuntime(12942): 	at nl.xservices.plugins.accessor.CalendarProviderAccessor.createEvent(CalendarProviderAccessor.java:98)
02-02 09:07:55.251: E/AndroidRuntime(12942): 	at nl.xservices.plugins.Calendar$9.run(Calendar.java:515)
02-02 09:07:55.251: E/AndroidRuntime(12942): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-02 09:07:55.251: E/AndroidRuntime(12942): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-02 09:07:55.251: E/AndroidRuntime(12942): 	at java.lang.Thread.run(Thread.java:818)


I hope it's enough?

**Comment by EddyVerbruggen** [comment] 2017-02-02 12:12
Thanks for the details. You have 2 options:

- Update your plugin config to reference https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin instead of using the one on npm
- Pass in `"allday": "false"` as one of the options (similar to `firstReminderMinutes`).

**Comment by RenateM** [comment] 2017-02-03 07:26
After updating the plugin, the problem is now resolved.

Thanks @EddyVerbruggen !

**Comment by EddyVerbruggen** [comment] 2017-02-03 08:59
Nice, it will be part of the next official release.

**Closed by EddyVerbruggen** 2017-02-03 08:59 UTC
